# Generated by Django 2.2 on 2020-09-10 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default='', max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('VIN', models.CharField(default='', max_length=10)),
                ('purchaseDate', models.DateTimeField(blank=True, default='', null=True)),
                ('lastServiceDate', models.DateTimeField(blank=True, default='', null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
    ]
